maintenance/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('maintenance/', include('maintenanceapp.urls'))
]

maintenanceapp/urls.py
from django.urls import path
from . import views

app_name = 'maintenanceapp'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('maintenance-create/', views.BreakdownMaintenanceWorkView.as_view(), 
        name='maintenance-create'),
    path('maintenance-record-create/', views.MaintenanceRecordView.as_view(), 
        name='maintenance-record-create'),
    path('preventative-create/', views.PreventativeMaintenaceWorkView.as_view(),
        name='preventative-create'),
    path('checklist-create/', views.MaintenanceChecklistCreate.as_view(),
        name='checklist-create'),
    path('checklistitem-create/', views.ChecklistItemCreate.as_view(),
        name='checklistitem-create'),
    path('maintenance-detail/<int:pk>', 
        views.BreakdownMaintenanceWorkDetailView.as_view(),
        name='maintenance-detail'),
    path('maintenance-record-detail/<int:pk>', 
        views.MaintenanceRecordDetailView.as_view(),    
        name='maintenance-record-detail'),
    path('preventative-detail/<int:pk>', 
        views.PreventativeMaintenanceWorkDetailView.as_view(),
        name='preventative-detail'),
    path('checklist-detail/<int:pk>',views.MaintenanceChecklistDetail.as_view(),
        name='checklist-detail'),
    path('checklistitem-detail/<int:pk>',views.ChecklistItemDetail.as_view(),
        name='checklistitem-detail'),
    path('maintenance-update/<int:pk>',
        views.BreakdownMaintenanceWorkUpdateView.as_view(),
        name='maintenance-update'),
    path('maintenance-record-update/<int:pk>',
        views.MaintenanceRecordUpdateView.as_view(),
        name='maintenance-record-update'),
    path('preventative-update/<int:pk>',
        views.PreventativeMaintenanceWorkUpdateView.as_view(),
        name='preventative-update'),
    path('checklist-update/<int:pk>',views.MaintenanceChecklistUpdate.as_view(),
        name='checklist-update'),
    path('checklistitem-update/<int:pk>',views.ChecklistItemUpdate.as_view(),
        name='checklistitem-update'),
    path('maintenance-list',views.BreakdownMaintenanceWorkRequestList.as_view(),
        name='maintenance-list'),
    path('maintenance-record-list',views.MaintenanceRecordlist.as_view(),
        name='maintenance-record-list'),
    path('preventative-list',views.PreventativeMaintenanceWorklist.as_view(),
        name='preventative-list'),
    path('checklist-list',views.MaintenanceChecklistList.as_view(),
        name='checklist-list'),
    path('checklistitem-list',views.ChecklistItemList.as_view(),
        name='checklistitem-list'),
    path('maintenance/<int:pk>/delete', 
        views.BreakdownMaintenanceWorkDelete.as_view(),
        name='maintenance-delete'),
    path('maintenance-record/<int:pk>/delete', 
        views.MaintenanceRecordDelete.as_view(),
        name='maintenance-record-delete'),
    path('preventative/<int:pk>/delete', 
        views.PreventativeMaintenanceDelete.as_view(),
        name='preventative-delete'),
    path('checklist/<int:pk>/delete', views.MaintenaceChecklistDelete.as_view(),
        name='checklist-delete'),
    path('checklistitem/<int:pk>/delete', views.ChecklistItemDelete.as_view(),
        name='checklistitem-delete'),
]

maintenanceapp/models.py
from django.db import models
from django.urls import reverse
# Create your models here.

class MaintenanceWorkRequest(models.Model):
    class Meta:
        abstract=True

    description = models.CharField(max_length=20, null=True, blank=True)
    created_by = models.CharField(max_length=20)
    category = models.CharField(max_length=20, choices=[
        ('Electrical','Electrical'),
        ('Mechanical','Mechanical'),
        ('Automotive','Automotive'),
        ('Plumbing','Plumbing'),
        ('Carpentry','Carpentry'),
    ])
    down_time = models.TimeField(null=True)
    labour_time = models.TimeField(null=True)
    team = models.CharField(max_length=24)
    responsible = models.CharField(max_length=24)
    duration = models.TimeField(null=True)
    consumables_required = models.TextField(max_length=256)
    resolved_by_vendor = models.BooleanField(default=False)
    vendor = models.CharField(max_length=255)
    service_order_ref = models.CharField(max_length=255)

class BreakdownMaintenanceWorkRequest(MaintenanceWorkRequest):
    
    def get_absolute_url(self):
        return reverse("maintenanceapp:maintenance-detail", kwargs={"pk": self.pk})

class PreventativeMaintenanceWorkRequest(MaintenanceWorkRequest):
    scheduled_date = models.DateField()
    down_time = models.TimeField()
    labour_time = models.TimeField()
    tasks = models.CharField(max_length=264)

    def get_absolute_url(self):
        return reverse("maintenanceapp:preventative-detail", kwargs={"pk": self.pk})

class MaintenanceRecord(models.Model):
    breakdown = models.ForeignKey(BreakdownMaintenanceWorkRequest, on_delete=models.CASCADE)
    planned_job = models.ForeignKey(PreventativeMaintenanceWorkRequest, on_delete=models.CASCADE)
    resolver = models.CharField(max_length=32)
    status = models.CharField(max_length=32, choices=[
        ('In Progress','In Progress'),
        ('Rejected','Rejected'),
        ('Approved','Approved'),
    ])
    approved_by = models.CharField(max_length=32)
    approved_date = models.DateField()
    consumables_used = models.TextField()

    def get_absolute_url(self):
        return reverse("maintenanceapp:maintenance-record-detail", kwargs={"pk": self.pk})

class MaintenanceChecklist(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    start_time = models.TimeField()
    start_date = models.DateField()
    frequency = models.CharField(max_length=24)
    duration = models.DurationField()
    category = models.CharField(max_length=255, choices=[
        ('electrical','Electrical'),
        ('mechanical','Mechanical'),
        ('automotive','Automotive'),
        ('plumbing','Plumbing'),
        ('carpentry','Carpentry'),
        ('hydraulics','Hydraulics'),
        ('pneumatics','Pneumatics'),
    ])
    resolver = models.CharField(max_length=32)

    def get_absolute_url(self):
        return reverse("maintenanceapp:checklist-detail", kwargs={"pk": self.pk})
    

class ChecklistItem(models.Model):
    checklist = models.ForeignKey(MaintenanceChecklist, on_delete = models.CASCADE)
    description = models.TextField()

    def get_absolute_url(self):
        return reverse("maintenanceapp:checklistitem-detail", kwargs={"pk": self.pk})

maintenanceapp/forms.py
from django.forms import ModelForm
from django import forms
from .models import *
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row,Column, HTML
from crispy_forms.bootstrap import Tab, TabHolder

class BreakdownMaintenaceWorkRequestForm(forms.ModelForm):
    class Meta:
        model = BreakdownMaintenanceWorkRequest
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            HTML(
                "<h4>Breakdown Maintenance Work Request Form </h4>"
            ),
            Row(
                Column(HTML('<h4>Basic</h4>'),css_class='col-6'),
                Column(HTML("<h4>Additional</h4>"), css_class='col-6'),
            ),
            Row(
                Column('created_by', 'category', 'down_time', 'labour_time', 'vendor', css_class='form-group col-md-6'),
                Column('team', 'responsible', 'duration', 'service_order_ref', css_class='form-group col-md-6')
            ),
            Row(
                Column('consumables_required', css_class='form-group col-md-12'),
            ),
        )
        self.helper.add_input(Submit('submit', "Submit"))

class PreventativeMaintenanceWorkRequestForm(forms.ModelForm):
    class Meta:
        model = PreventativeMaintenanceWorkRequest
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            HTML(
                "<h4>Maintenance Work Request Form </h4>"
            ),
            Row(
                Column(HTML('<h4>Basic</h4>'),css_class='col-6'),
                Column(HTML("<h4>Additional</h4>"), css_class='col-6'),
            ),
            Row(
                Column('created_by', 'category', 'down_time', 'labour_time', 'scheduled_date', css_class='form-group col-md-6', label='e.g Kitchen Maintenance'),
                Column('team', 'responsible', 'duration', 'service_order_ref',
                'vendor','tasks', css_class='form-group col-md-6')
            ),
            Row(
                Column('consumables_required', css_class='form-group col-md-12'),
            ),
        )
        self.helper.add_input(Submit('submit', "Submit"))

class MaintenanceRecordForm(forms.ModelForm):
    class Meta:
        model = MaintenanceRecord
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            HTML(
                "<h4>Maintenance Record Form </h4>"
            ),
            Row(
                Column(HTML('<h4>Basic</h4>'),css_class='col-6'),
                Column(HTML("<h4>Additional</h4>"), css_class='col-6'),
            ),
            Row(
                Column('planned_job', 'approved_by', css_class='form-group col-md-6'),
                Column('status', 'approved_date', css_class='form-group col-md-6'),
            ),
            Row(
                Column('resolver', css_class='form-group col-md-6'),
                Column('breakdown', css_class='form-group col-md-6'),
            ),
            Row(
                Column('consumables_used', css_class='form-group col-md-12'),
            ),
        )
        self.helper.add_input(Submit('submit', "Submit"))

class MaintenanceCheklistForm(forms.ModelForm):
    class Meta:
        model = MaintenanceChecklist
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].label = "e.g Kitchen Checklist"
        self.helper = FormHelper()
        self.helper.layout = Layout(
            HTML(
                "<h3>Maintenance Checklist Form </h3>"
            ),
            Row(
                Column(HTML('<h4>Main</h4>'),css_class='col-6'),
                Column(HTML('<h4>Details</h4>'),css_class='col-6'),
            ),
            Row(
                Column('name','resolver','category',css_class='form-group col-md-6'),
                Column('start_time','start_date','frequency','duration',css_class='form-group col-md-6'),                
            ),
            'description'
        )
        self.helper.add_input(Submit('submit', "Submit"))

class CheklistItemForm(forms.ModelForm):
    class Meta:
        model = ChecklistItem
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            HTML(
                "<h3>Checklist Item Form </h3>"
            ),
            'checklist',
            'description',
        )
        self.helper.add_input(Submit('submit', "Submit"))

maintenanceapp/views.py
from django.shortcuts import render
from django import forms
from django.urls import reverse_lazy
from .forms import *
from django.views.generic import CreateView, DetailView, ListView, DeleteView, UpdateView
from . import models
import os 

# Create your views here.

def dashboard(request):
    return render(request, 'dashboard.html')

class BreakdownMaintenanceWorkView(CreateView):
    template_name = os.path.join('maintenanceapp','maintenance-work-request.html')
    form_class = BreakdownMaintenaceWorkRequestForm
    
class MaintenanceRecordView(CreateView):
    template_name = os.path.join('maintenanceapp','maintenance-record.html')
    form_class = MaintenanceRecordForm

class PreventativeMaintenaceWorkView(CreateView):
    template_name = os.path.join('maintenanceapp','preventative-maintenance.html')
    form_class = PreventativeMaintenanceWorkRequestForm

class MaintenanceChecklistCreate(CreateView):
    template_name = os.path.join('maintenanceapp','maintenance-checklist.html')
    form_class = MaintenanceCheklistForm

class ChecklistItemCreate(CreateView):
    template_name = os.path.join('maintenanceapp','checklistitem.html')
    form_class = CheklistItemForm

class BreakdownMaintenanceWorkDetailView(DetailView):
    model = models.BreakdownMaintenanceWorkRequest
    template_name = os.path.join('detail','work-request-detail.html')

class PreventativeMaintenanceWorkDetailView(DetailView):
    model = models.PreventativeMaintenanceWorkRequest
    template_name = os.path.join('detail','preventative-detail.html')

class MaintenanceRecordDetailView(DetailView):
    model = models.MaintenanceRecord
    template_name = os.path.join('detail','record-detail.html')

class MaintenanceChecklistDetail(DetailView):
    model = models.MaintenanceChecklist
    template_name = os.path.join('detail','checklist-detail.html')

class ChecklistItemDetail(DetailView):
    model = models.ChecklistItem
    template_name = os.path.join('detail','checklistitem-detail.html')

class BreakdownMaintenanceWorkRequestList(ListView):
    template_name = os.path.join('list', 'maintenance-list.html')
    context_object_name = 'work'

    def get_queryset(self):
        return models.BreakdownMaintenanceWorkRequest.objects.order_by('pk')

class PreventativeMaintenanceWorklist(ListView):
    template_name = os.path.join('list', 'preventative-list.html')
    context_object_name = 'preventative'

    def get_queryset(self):
        return models.PreventativeMaintenanceWorkRequest.objects.order_by('pk')

class MaintenanceRecordlist(ListView):
    template_name = os.path.join('list', 'maintenance-record-list.html')
    context_object_name = 'record'

    def get_queryset(self):
        return models.MaintenanceRecord.objects.order_by('pk')

class MaintenanceChecklistList(ListView):
    template_name = os.path.join('list','maintenance-checklist-list.html')

    def get_queryset(self):
        return models.MaintenanceChecklist.objects.order_by('pk')

class ChecklistItemList(ListView):
    template_name = os.path.join('list','checklistitem-list.html')

    def get_queryset(self):
        return models.ChecklistItem.objects.order_by('pk')

class BreakdownMaintenanceWorkUpdateView(UpdateView):
    form_class = BreakdownMaintenaceWorkRequestForm
    model = models.BreakdownMaintenanceWorkRequest
    template_name = os.path.join('maintenanceapp','maintenance-work-request.html')

class PreventativeMaintenanceWorkUpdateView(UpdateView):
    form_class = PreventativeMaintenanceWorkRequestForm
    model = models.PreventativeMaintenanceWorkRequest
    template_name = os.path.join('maintenanceapp','preventative-maintenance.html')

class MaintenanceRecordUpdateView(UpdateView):
    form_class = MaintenanceRecordForm
    model = models.MaintenanceRecord
    template_name = os.path.join('maintenanceapp','maintenance-record.html')

class MaintenanceChecklistUpdate(UpdateView):
    form_class = MaintenanceCheklistForm
    model = models.MaintenanceChecklist
    template_name = os.path.join('maintenanceapp','maintenance-checklist.html')

class ChecklistItemUpdate(UpdateView):
    form_class = CheklistItemForm
    model = models.ChecklistItem
    template_name = os.path.join('maintenanceapp','checklistItem.html')

class BreakdownMaintenanceWorkDelete(DeleteView):
    template_name = os.path.join('maintenanceapp','maintenance_confirm_delete.html')
    model = models.BreakdownMaintenanceWorkRequest
    success_url = reverse_lazy('maintenanceapp:maintenance-list')

class MaintenanceRecordDelete(DeleteView):
    template_name = os.path.join('maintenanceapp','maintenance_record_confirm_delete.html')
    model = models.MaintenanceRecord
    success_url = reverse_lazy('maintenanceapp:maintenance-record-list')

class PreventativeMaintenanceDelete(DeleteView):
    template_name = os.path.join('maintenanceapp',
    'preventative_confirm_delete.html')
    model = models.PreventativeMaintenanceWorkRequest
    success_url = reverse_lazy('maintenanceapp:preventative-list')

class MaintenaceChecklistDelete(DeleteView):
    template_name = os.path.join('maintenanceapp','checklist_confirm_delete.html')
    model = models.MaintenanceChecklist
    success_url = reverse_lazy('maintenanceapp:checklist-list')

class ChecklistItemDelete(DeleteView):
    template_name = os.path.join('maintenanceapp','checklistitem_confirm_delete.html')
    model = models.ChecklistItem
    success_url = reverse_lazy('maintenanceapp:checklistitem-list')

maintenanceapp/templates/list/checklistitem-list.html
{% extends 'nav.html' %}

{% block list_headings %}

    <tr>
        <td class="info">Checklist</td>
        <td class="info">Actions</td>
    </tr>

{% endblock  %}

{% block list_content %}

    <tr>
        {% for object in object_list %}
            <td>{{object.checklist}}</td>
            <td><div class="dropdown">
            <button class="btn btn-primary btn-sm dropdown-toggle" type="button" id="triggerId" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                Actions
            </button>
            <div class="dropdown-menu" aria-labelledby="triggerId">
                <a class="dropdown-item" href="{% url 'maintenanceapp:checklistitem-detail' pk=object.pk%}">
                    <i class="fas fa-eye"></i> Detail
                </a>
                <a class="dropdown-item" href="{% url 'maintenanceapp:checklistitem-update' pk=object.pk%}">
                    <i class="fas fa-edit"></i> Update
                </a>
                <a class="dropdown-item" href="{% url 'maintenanceapp:checklistitem-delete' pk=object.pk%}">
                    <i class="fas fa-trash"></i> Delete
                </a>
            </div>
        </div>
        </td>
    </tr>
{% endfor %}
{% endblock  %}

maintenanceapp/templates/list/maintenance-checklist-list.html
{% extends 'nav.html' %}

{% block list_headings %}

    <tr>
        <td class="info">Name</td>
        <td class="info">Category</td>
        <td class="info">Resolver</td>
        <td class="info">Start Date</td>
        <td class="info">Actions</td>
    </tr>

{% endblock  %}

{% block list_content %}

    <tr>
        {% for object in object_list %}
            <td>{{object.name}}</td>
            <td>{{object.category}}</td>
            <td>{{object.resolver}}</td>
            <td>{{object.startt_date}}</td>
            <td><div class="dropdown">
            <button class="btn btn-primary btn-sm dropdown-toggle" type="button" id="triggerId" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                Actions
            </button>
            <div class="dropdown-menu" aria-labelledby="triggerId">
                <a class="dropdown-item" href="{% url 'maintenanceapp:checklist-detail' pk=object.pk%}">
                    <i class="fas fa-eye"></i> Detail
                </a>
                <a class="dropdown-item" href="{% url 'maintenanceapp:checklist-update' pk=object.pk%}">
                    <i class="fas fa-edit"></i> Update
                </a>
                <a class="dropdown-item" href="{% url 'maintenanceapp:checklist-delete' pk=object.pk%}">
                    <i class="fas fa-trash"></i> Delete
                </a>
            </div>
        </div>
        </td>
    </tr>
{% endfor %}
{% endblock  %}

maintenanceapp/templates/list/maintenance-list.html
{% extends 'nav.html' %}

{% block list_headings %}

    <tr>
        <td class="info">Created By</td>
        <td class="info">Category</td>
        <td class="info">Down Time</td>
        <td class="info">Actions</td>
    </tr>

{% endblock  %}

{% block list_content %}

    <tr>
        {% for object in object_list %}
            <td>{{object.created_by}}</td>
            <td>{{object.category}}</td>
            <td>{{object.down_time}}</td>
            <td><div class="dropdown">
            <button class="btn btn-primary btn-sm dropdown-toggle" type="button" id="triggerId" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                Actions
            </button>
            <div class="dropdown-menu" aria-labelledby="triggerId">
                <a class="dropdown-item" href="{% url 'maintenanceapp:maintenance-detail' pk=object.pk%}">
                    <i class="fas fa-eye"></i> Detail
                </a>
                <a class="dropdown-item" href="{% url 'maintenanceapp:maintenance-update' pk=object.pk%}">
                    <i class="fas fa-edit"></i> Update
                </a>
                <a class="dropdown-item" href="{% url 'maintenanceapp:maintenance-delete' pk=object.pk%}">
                    <i class="fas fa-trash"></i> Delete
                </a>
            </div>
        </div>
        </td>
    </tr>
{% endfor %}
{% endblock  %}

maintenanceapp/templates/list/maintenance-record-list.html
{% extends 'nav.html' %}

{% block list_headings %}

    <tr>
        <td class="info">Planned Job</td>
        <td class="info">Resolver</td>
        <td class="info">Approved By</td>
        <td class="info">Approved Date</td>
        <td class="info">Actions</td>
    </tr>

{% endblock  %}

{% block list_content %}

    <tr>
        {% for record in object_list %}
            <td>{{record.planned_job}}</td>
            <td>{{record.resolver}}</td>
            <td>{{record.approved_by}}</td>
            <td>{{record.approved_date}}</td>
            <td><div class="dropdown">
            <button class="btn btn-primary btn-sm dropdown-toggle" type="button" id="triggerId" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                Actions
            </button>
            <div class="dropdown-menu" aria-labelledby="triggerId">
                <a class="dropdown-item" href="{% url 'maintenanceapp:maintenance-record-detail' pk=record.pk%}">
                    <i class="fas fa-eye"></i> Detail
                </a>
                <a class="dropdown-item" href="{% url 'maintenanceapp:maintenance-record-update' pk=record.pk%}">
                    <i class="fas fa-edit"></i> Update
                </a>
                <a class="dropdown-item" href="{% url 'maintenanceapp:maintenance-delete' pk=record.pk%}">
                    <i class="fas fa-trash"></i> Delete
                </a>
            </div>
        </div>
        </td>
    </tr>
{% endfor %}
{% endblock  %}

maintenanceapp/templates/list/preventative-list.html
{% extends 'nav.html' %}

{% block list_headings %}

    <tr>
        <td class="info">Scheduled Date</td>
        <td class="info">Down Time</td>
        <td class="info">Labour Time</td>
        <td class="info">Tasks</td>
        <td class="info">Actions</td>
    </tr>

{% endblock  %}

{% block list_content %}

    <tr>
        {% for object in object_list %}
            <td>{{object.scheduled_date}}</td>
            <td>{{object.down_time}}</td>
            <td>{{object.labour_time}}</td>
            <td>{{object.tasks}}</td>
            <td><div class="dropdown">
            <button class="btn btn-primary btn-sm dropdown-toggle" type="button" id="triggerId" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                Actions
            </button>
            <div class="dropdown-menu" aria-labelledby="triggerId">
                <a class="dropdown-item" href="{% url 'maintenanceapp:preventative-detail' pk=object.pk%}">
                    <i class="fas fa-eye"></i> Detail
                </a>
                <a class="dropdown-item" href="{% url 'maintenanceapp:preventative-update' pk=object.pk%}">
                    <i class="fas fa-edit"></i> Update
                </a>
                <a class="dropdown-item" href="{% url 'maintenanceapp:preventative-delete' pk=object.pk%}">
                    <i class="fas fa-trash"></i> Delete
                </a>
            </div>
        </div>
        </td>
    </tr>
{% endfor %}
{% endblock  %}