maintenance/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('maintenance/', include('maintenanceapp.urls'))
]

maintenanceapp/urls.py
from django.urls import path
from . import views

app_name = 'maintenanceapp'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('maintenance-create/', views.BreakdownMaintenanceWorkView.as_view(), 
        name='maintenance-create'),
    path('maintenance-record-create/', views.MaintenanceRecordView.as_view(), 
        name='maintenance-record-create'),
    path('preventative-create/', views.PreventativeMaintenaceWorkView.as_view(),
        name='preventative-create'),
    path('checklist-create/', views.MaintenanceChecklistCreate.as_view(),
        name='checklist-create'),
    path('checklistitem-create/', views.ChecklistItemCreate.as_view(),
        name='checklistitem-create'),
    path('maintenance-detail/<int:pk>', 
        views.BreakdownMaintenanceWorkDetailView.as_view(),
        name='maintenance-detail'),
    path('maintenance-record-detail/<int:pk>', 
        views.MaintenanceRecordDetailView.as_view(),    
        name='maintenance-record-detail'),
    path('preventative-detail/<int:pk>', 
        views.PreventativeMaintenanceWorkDetailView.as_view(),
        name='preventative-detail'),
    path('checklist-detail/<int:pk>',views.MaintenanceChecklistDetail.as_view(),
        name='checklist-detail'),
    path('checklistitem-detail/<int:pk>',views.ChecklistItemDetail.as_view(),
        name='checklistitem-detail'),
    path('maintenance-update/<int:pk>',
        views.BreakdownMaintenanceWorkUpdateView.as_view(),
        name='maintenance-update'),
    path('maintenance-record-update/<int:pk>',
        views.MaintenanceRecordUpdateView.as_view(),
        name='maintenance-record-update'),
    path('preventative-update/<int:pk>',
        views.PreventativeMaintenanceWorkUpdateView.as_view(),
        name='preventative-update'),
    path('checklist-update/<int:pk>',views.MaintenanceChecklistUpdate.as_view(),
        name='checklist-update'),
    path('checklistitem-update/<int:pk>',views.ChecklistItemUpdate.as_view(),
        name='checklistitem-update'),
    path('maintenance-list',views.BreakdownMaintenanceWorkRequestList.as_view(),
        name='maintenance-list'),
    path('maintenance-record-list',views.MaintenanceRecordlist.as_view(),
        name='maintenance-record-list'),
    path('preventative-list',views.PreventativeMaintenanceWorklist.as_view(),
        name='preventative-list'),
    path('checklist-list',views.MaintenanceChecklistList.as_view(),
        name='checklist-list'),
    path('checklistitem-list',views.ChecklistItemList.as_view(),
        name='checklistitem-list'),
    path('maintenance/<int:pk>/delete', 
        views.BreakdownMaintenanceWorkDelete.as_view(),
        name='maintenance-delete'),
    path('maintenance-record/<int:pk>/delete', 
        views.MaintenanceRecordDelete.as_view(),
        name='maintenance-record-delete'),
    path('preventative/<int:pk>/delete', 
        views.PreventativeMaintenanceDelete.as_view(),
        name='preventative-delete'),
    path('checklist/<int:pk>/delete', views.MaintenaceChecklistDelete.as_view(),
        name='checklist-delete'),
    path('checklistitem/<int:pk>/delete', views.ChecklistItemDelete.as_view(),
        name='checklistitem-delete'),
]

maintenanceapp/models.py
from django.db import models
from django.urls import reverse
# Create your models here.

class MaintenanceWorkRequest(models.Model):
    class Meta:
        abstract=True

    description = models.CharField(max_length=20, null=True, blank=True)
    created_by = models.CharField(max_length=20)
    category = models.CharField(max_length=20, choices=[
        ('Electrical','Electrical'),
        ('Mechanical','Mechanical'),
        ('Automotive','Automotive'),
        ('Plumbing','Plumbing'),
        ('Carpentry','Carpentry'),
    ])
    down_time = models.TimeField(null=True)
    labour_time = models.TimeField(null=True)
    team = models.CharField(max_length=24)
    responsible = models.CharField(max_length=24)
    duration = models.TimeField(null=True)
    consumables_required = models.TextField(max_length=256)
    resolved_by_vendor = models.BooleanField(default=False)
    vendor = models.CharField(max_length=255)
    service_order_ref = models.CharField(max_length=255)

class BreakdownMaintenanceWorkRequest(MaintenanceWorkRequest):
    
    def get_absolute_url(self):
        return reverse("maintenanceapp:maintenance-detail", kwargs={"pk": self.pk})

class PreventativeMaintenanceWorkRequest(MaintenanceWorkRequest):
    scheduled_date = models.DateField()
    down_time = models.TimeField()
    labour_time = models.TimeField()
    tasks = models.CharField(max_length=264)

    def get_absolute_url(self):
        return reverse("maintenanceapp:preventative-detail", kwargs={"pk": self.pk})

class MaintenanceRecord(models.Model):
    breakdown = models.ForeignKey(BreakdownMaintenanceWorkRequest, on_delete=models.CASCADE)
    planned_job = models.ForeignKey(PreventativeMaintenanceWorkRequest, on_delete=models.CASCADE)
    resolver = models.CharField(max_length=32)
    status = models.CharField(max_length=32, choices=[
        ('In Progress','In Progress'),
        ('Rejected','Rejected'),
        ('Approved','Approved'),
    ])
    approved_by = models.CharField(max_length=32)
    approved_date = models.DateField()
    consumables_used = models.TextField()

    def get_absolute_url(self):
        return reverse("maintenanceapp:maintenance-record-detail", kwargs={"pk": self.pk})

class MaintenanceChecklist(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    start_time = models.TimeField()
    start_date = models.DateField()
    frequency = models.CharField(max_length=24)
    duration = models.DurationField()
    category = models.CharField(max_length=255, choices=[
        ('electrical','Electrical'),
        ('mechanical','Mechanical'),
        ('automotive','Automotive'),
        ('plumbing','Plumbing'),
        ('carpentry','Carpentry'),
        ('hydraulics','Hydraulics'),
        ('pneumatics','Pneumatics'),
    ])
    resolver = models.CharField(max_length=32)

    def get_absolute_url(self):
        return reverse("maintenanceapp:checklist-detail", kwargs={"pk": self.pk})
    

class ChecklistItem(models.Model):
    checklist = models.ForeignKey(MaintenanceChecklist, on_delete = models.CASCADE)
    description = models.TextField()

    def get_absolute_url(self):
        return reverse("maintenanceapp:checklistitem-detail", kwargs={"pk": self.pk})

maintenanceapp/forms.py
from django.forms import ModelForm
from django import forms
from .models import *
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row,Column, HTML
from crispy_forms.bootstrap import Tab, TabHolder

class BreakdownMaintenaceWorkRequestForm(forms.ModelForm):
    class Meta:
        model = BreakdownMaintenanceWorkRequest
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            HTML(
                "<h4>Breakdown Maintenance Work Request Form </h4>"
            ),
            Row(
                Column(HTML('<h4>Basic</h4>'),css_class='col-6'),
                Column(HTML("<h4>Additional</h4>"), css_class='col-6'),
            ),
            Row(
                Column('created_by', 'category', 'down_time', 'labour_time', 'vendor', css_class='form-group col-md-6'),
                Column('team', 'responsible', 'duration', 'service_order_ref', css_class='form-group col-md-6')
            ),
            Row(
                Column('consumables_required', css_class='form-group col-md-12'),
            ),
        )
        self.helper.add_input(Submit('submit', "Submit"))

class PreventativeMaintenanceWorkRequestForm(forms.ModelForm):
    class Meta:
        model = PreventativeMaintenanceWorkRequest
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            HTML(
                "<h4>Maintenance Work Request Form </h4>"
            ),
            Row(
                Column(HTML('<h4>Basic</h4>'),css_class='col-6'),
                Column(HTML("<h4>Additional</h4>"), css_class='col-6'),
            ),
            Row(
                Column('created_by', 'category', 'down_time', 'labour_time', 'scheduled_date', css_class='form-group col-md-6', label='e.g Kitchen Maintenance'),
                Column('team', 'responsible', 'duration', 'service_order_ref',
                'vendor','tasks', css_class='form-group col-md-6')
            ),
            Row(
                Column('consumables_required', css_class='form-group col-md-12'),
            ),
        )
        self.helper.add_input(Submit('submit', "Submit"))

class MaintenanceRecordForm(forms.ModelForm):
    class Meta:
        model = MaintenanceRecord
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            HTML(
                "<h4>Maintenance Record Form </h4>"
            ),
            Row(
                Column(HTML('<h4>Basic</h4>'),css_class='col-6'),
                Column(HTML("<h4>Additional</h4>"), css_class='col-6'),
            ),
            Row(
                Column('planned_job', 'approved_by', css_class='form-group col-md-6'),
                Column('status', 'approved_date', css_class='form-group col-md-6'),
            ),
            Row(
                Column('resolver', css_class='form-group col-md-6'),
                Column('breakdown', css_class='form-group col-md-6'),
            ),
            Row(
                Column('consumables_used', css_class='form-group col-md-12'),
            ),
        )
        self.helper.add_input(Submit('submit', "Submit"))

class MaintenanceCheklistForm(forms.ModelForm):
    class Meta:
        model = MaintenanceChecklist
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].label = "e.g Kitchen Checklist"
        self.helper = FormHelper()
        self.helper.layout = Layout(
            HTML(
                "<h3>Maintenance Checklist Form </h3>"
            ),
            Row(
                Column(HTML('<h4>Main</h4>'),css_class='col-6'),
                Column(HTML('<h4>Details</h4>'),css_class='col-6'),
            ),
            Row(
                Column('name','resolver','category',css_class='form-group col-md-6'),
                Column('start_time','start_date','frequency','duration',css_class='form-group col-md-6'),                
            ),
            'description'
        )
        self.helper.add_input(Submit('submit', "Submit"))

class CheklistItemForm(forms.ModelForm):
    class Meta:
        model = ChecklistItem
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            HTML(
                "<h3>Checklist Item Form </h3>"
            ),
            'checklist',
            'description',
        )
        self.helper.add_input(Submit('submit', "Submit"))

maintenanceapp/views.py
from django.shortcuts import render
from django import forms
from django.urls import reverse_lazy
from .forms import *
from django.views.generic import CreateView, DetailView, ListView, DeleteView, UpdateView
from . import models
import os 

# Create your views here.

def dashboard(request):
    return render(request, 'dashboard.html')

class BreakdownMaintenanceWorkView(CreateView):
    template_name = os.path.join('maintenanceapp','maintenance-work-request.html')
    form_class = BreakdownMaintenaceWorkRequestForm
    
class MaintenanceRecordView(CreateView):
    template_name = os.path.join('maintenanceapp','maintenance-record.html')
    form_class = MaintenanceRecordForm

class PreventativeMaintenaceWorkView(CreateView):
    template_name = os.path.join('maintenanceapp','preventative-maintenance.html')
    form_class = PreventativeMaintenanceWorkRequestForm

class MaintenanceChecklistCreate(CreateView):
    template_name = os.path.join('maintenanceapp','maintenance-checklist.html')
    form_class = MaintenanceCheklistForm

class ChecklistItemCreate(CreateView):
    template_name = os.path.join('maintenanceapp','checklistitem.html')
    form_class = CheklistItemForm

class BreakdownMaintenanceWorkDetailView(DetailView):
    model = models.BreakdownMaintenanceWorkRequest
    template_name = os.path.join('detail','work-request-detail.html')

class PreventativeMaintenanceWorkDetailView(DetailView):
    model = models.PreventativeMaintenanceWorkRequest
    template_name = os.path.join('detail','preventative-detail.html')

class MaintenanceRecordDetailView(DetailView):
    model = models.MaintenanceRecord
    template_name = os.path.join('detail','record-detail.html')

class MaintenanceChecklistDetail(DetailView):
    model = models.MaintenanceChecklist
    template_name = os.path.join('detail','checklist-detail.html')

class ChecklistItemDetail(DetailView):
    model = models.ChecklistItem
    template_name = os.path.join('detail','checklistitem-detail.html')

class BreakdownMaintenanceWorkRequestList(ListView):
    template_name = os.path.join('list', 'maintenance-list.html')
    context_object_name = 'work'

    def get_queryset(self):
        return models.BreakdownMaintenanceWorkRequest.objects.order_by('pk')

class PreventativeMaintenanceWorklist(ListView):
    template_name = os.path.join('list', 'preventative-list.html')
    context_object_name = 'preventative'

    def get_queryset(self):
        return models.PreventativeMaintenanceWorkRequest.objects.order_by('pk')

class MaintenanceRecordlist(ListView):
    template_name = os.path.join('list', 'maintenance-record-list.html')
    context_object_name = 'record'

    def get_queryset(self):
        return models.MaintenanceRecord.objects.order_by('pk')

class MaintenanceChecklistList(ListView):
    template_name = os.path.join('list','maintenance-checklist-list.html')

    def get_queryset(self):
        return models.MaintenanceChecklist.objects.order_by('pk')

class ChecklistItemList(ListView):
    template_name = os.path.join('list','checklistitem-list.html')

    def get_queryset(self):
        return models.ChecklistItem.objects.order_by('pk')

class BreakdownMaintenanceWorkUpdateView(UpdateView):
    form_class = BreakdownMaintenaceWorkRequestForm
    model = models.BreakdownMaintenanceWorkRequest
    template_name = os.path.join('maintenanceapp','maintenance-work-request.html')

class PreventativeMaintenanceWorkUpdateView(UpdateView):
    form_class = PreventativeMaintenanceWorkRequestForm
    model = models.PreventativeMaintenanceWorkRequest
    template_name = os.path.join('maintenanceapp','preventative-maintenance.html')

class MaintenanceRecordUpdateView(UpdateView):
    form_class = MaintenanceRecordForm
    model = models.MaintenanceRecord
    template_name = os.path.join('maintenanceapp','maintenance-record.html')

class MaintenanceChecklistUpdate(UpdateView):
    form_class = MaintenanceCheklistForm
    model = models.MaintenanceChecklist
    template_name = os.path.join('maintenanceapp','maintenance-checklist.html')

class ChecklistItemUpdate(UpdateView):
    form_class = CheklistItemForm
    model = models.ChecklistItem
    template_name = os.path.join('maintenanceapp','checklistItem.html')

class BreakdownMaintenanceWorkDelete(DeleteView):
    template_name = os.path.join('maintenanceapp','maintenance_confirm_delete.html')
    model = models.BreakdownMaintenanceWorkRequest
    success_url = reverse_lazy('maintenanceapp:maintenance-list')

class MaintenanceRecordDelete(DeleteView):
    template_name = os.path.join('maintenanceapp','maintenance_record_confirm_delete.html')
    model = models.MaintenanceRecord
    success_url = reverse_lazy('maintenanceapp:maintenance-record-list')

class PreventativeMaintenanceDelete(DeleteView):
    template_name = os.path.join('maintenanceapp',
    'preventative_confirm_delete.html')
    model = models.PreventativeMaintenanceWorkRequest
    success_url = reverse_lazy('maintenanceapp:preventative-list')

class MaintenaceChecklistDelete(DeleteView):
    template_name = os.path.join('maintenanceapp','checklist_confirm_delete.html')
    model = models.MaintenanceChecklist
    success_url = reverse_lazy('maintenanceapp:checklist-list')

class ChecklistItemDelete(DeleteView):
    template_name = os.path.join('maintenanceapp','checklistitem_confirm_delete.html')
    model = models.ChecklistItem
    success_url = reverse_lazy('maintenanceapp:checklistitem-list')

maintenanceapp/templates/dashboard.html
{% extends 'maintenance.html' %}
{% load static %}
{% block content %}

<div class="jumbotron jumbo-gradient">
    <h1 class="display-3">Maintenance Dashboard</h1>
</div>
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <ul class="nav nav-tabs">
                <li class="nav-item"><a href="" class="nav-link active" data-toggle="tab">Actions</a></li>
                <li class="nav-item"><a href="" class="nav-link active" data-toggle="tab">Dashboard</a></li>
            </ul>
            <div class="tab-content panel-body">
                <div id="actions" class="tab-pane active">
                    <div class="card-deck">
                        <div class="card bg-primary text-white">
                            <div class="card-header">
                                <h4 class="card-title">Maintenance Request</h4>
                            </div>
                            <div class="card-body">
                                <ul class="list-group">
                                    <li class="list-group-item hvr-grow"><a href="{% url 'maintenanceapp:maintenance-create'%}" class="card-link">Maintenance Work
                                            Request Form</a></li>
                                    <li class="list-group-item hvr-grow"><a href="{% url 'maintenanceapp:maintenance-list'%}" class="card-link">Maintenance
                                            List</a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="card bg-primary text-white">
                            <div class="card-header">
                                <h4 class="card-title">Maintenacnce Checklist</h4>
                            </div>
                            <div class="card-body">
                                <ul class="list-group">
                                    <li class="list-group-item hvr-grow"><a href="{% url 'maintenanceapp:checklist-create'%}" class="card-link">Maintenance Checklist Create</a></li>
                                    <li class="list-group-item hvr-grow"><a href="{% url 'maintenanceapp:checklist-list'%}" class="card-link">Maintenance CheckList</a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="card-deck">
                            <div class="card bg-primary text-white">
                                <div class="card-header">
                                    <h4 class="card-title">Preventative Work Request</h4>
                                </div>
                                <div class="card-body">
                                    <ul class="list-group">
                                        <li class="list-group-item hvr-grow"><a href="{% url 'maintenanceapp:preventative-create'%}" class="card-link">Create
                                                Preventative</a></li>
                                        <li class="list-group-item hvr-grow"><a href="{% url 'maintenanceapp:preventative-list' %}" class="card-link">Manage Preventative Work Requests</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>

                    <hr class="my-4">
                    <div class="card-deck">
                        <div class="card bg-primary text-white">
                            <div class="card-header">
                                <h4 class="card-title">Maintenance Records</h4>
                            </div>
                            <div class="card-body">
                                <ul class="list-group">
                                    <li class="list-group-item hvr-grow"><a href="{% url 'maintenanceapp:maintenance-record-create' %}" class="card-link">Create
                                            Record</a></li>
                                    <li class="list-group-item hvr-grow"><a href="{% url 'maintenanceapp:maintenance-record-list'%}" class="card-link">Manage
                                            Records</a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="card bg-primary text-white">
                            <div class="card-header">
                                <h4 class="card-title"> Checklist Item</h4>
                            </div>
                            <div class="card-body">
                                <ul class="list-group">
                                    <li class="list-group-item hvr-grow"><a href="{% url 'maintenanceapp:checklistitem-create'%}" class="card-link">Checklist Item Create</a></li>
                                    <li class="list-group-item hvr-grow"><a href="{% url 'maintenanceapp:checklistitem-list'%}" class="card-link"> CheckList Item List</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

{% endblock  %}

maintenanceapp/templates/maintenance.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script type="text/javascript" src="{% static 'maintenanceapp/js/popper.js' %}"></script>
    <script type="text/javascript" src="{% static 'maintenanceapp/js/jquery-3.3.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'maintenanceapp/js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'maintenanceapp/css/bootstrap.min.css' %}" />
    <title>Maintenance</title>
</head>      
<body>
    <div class="container">
    {% block content %}
    {% endblock %}
    </div>
</body>
</html>

maintenanceapp/templates/nav.html
{% extends "maintenance.html" %} 
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'maintenanceapp/css/filters.css' %}">
{% endblock %}
{% block content %}


<div class="jumbotron">
    <div class="container">
        <h1 class="display-3"><i class="fas fa-list"></i>List</h1>
        <p class="lead">{{description}}</p>
        <p></p>
            {% if new_link %}
            <a class="btn btn-primary btn-lg" href="{{new_link}}">Create New <i class="fas fa-pen"></i></a>
            {% endif %}    
        <p class="lead">
        </p>
    </div>
</div>


<div class="container">
    <div class="row">
        <div class="col-sm-12">
            {% block other%}{% endblock %}
        </div>
    </div>
    <div class="row">
        <div class="col-sm-3 col-md-3">
            {% if is_paginated %}
            
            {% endif %}

            <div class="card bg-primary text-white">
                <div class="card-header">
                    <h3 class="cart-title"><i class="fas fa-filter"></i> Filters</h3>
                </div>
                <div class="card-body">
                    <form action="" method="get">
                            {{filter.form.as_p}}
                            
                        <button class="btn btn-default pull-right" type="submit">Filter</button>
                    </form>
                </div>
            </div>
        </div>

        <div class="col-sm-9 col-md-9">
                <ul class="pagination pagination-lg">
                        {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{page_obj.previous_page_number}}">
                                <i class="fas fa-angle-left"></i>
                            </a>
                        </li>
                        {% else %}
                        <li class="page-item disabled">
                            <a class="page-link">
                                <i class="fas fa-angle-left"></i>
                            </a>
                        </li>
                        {% endif %} {% for i in paginator.page_range %} {% if page_obj.number == i %}
                        <li class="page-item active">
                            <a class="page-link">{{i}}</a>
                        </li>
                        {% else %}
                        <li>
                            <a class="page-link" href="?page={{i}}">{{i}}</a>
                        </li>
                        {% endif %} {% endfor %} {% if page_obj.has_next %}
                        <li class="page-item next">
                            <a class="page-link" href="?page={{page_obj.next_page_number}}">
                                <i class="fas fa-angle-right"></i>
                            </a>
                        </li>
                        {% else %}
                        <li class="page-item disabled">
                            <a class="page-link">
                                <i class="fas fa-angle-right"></i>
                            </a>
                        </li>
                        {% endif %}
        
                    </ul>

            {% if object_list.all.count == 0 %}
                <p><b>No items to display</b></p>
            {% else %}
            <table class="table table-sm table-striped  table-hover">
                <thead>
                    {% block list_headings %}{% endblock %}
                </thead>
                <tbody>
                        {% block list_content %}{% endblock %}
                </tbody>
            </table>
            {% endif %}

        </div>
    </div>

</div>
<script>
    $('input').addClass('form-control');
    $('select').addClass('form-control');
    $('#id_date').datepicker({
        changeYear: true,
        dateFormat: 'yy-mm-dd'  });
    $('#id_expected_receipt_date').datepicker({
        changeYear: true,
        dateFormat: 'yy-mm-dd' });
</script>
{% endblock %}